### ISSUE TITLE
Add new states to existing RMs

### ISSUE THREAD

**Issue by GomathiselviS** [ansible-collections/arista.eos#23]
##### SUMMARY
Add **gathered** , **parsed** and **rendered** to the following resource modules.

- [x]  eos_interfaces (https://github.com/ansible-collections/arista.eos/pull/24)
- [x] eos_l2_interfaces (https://github.com/ansible-collections/arista.eos/pull/26)
- [x] eos_l3_interfaces (https://github.com/ansible-collections/arista.eos/pull/27)
- [x] eos_lacp (#30)
- [x] eos_lacp_interfaces (#31)
- [x] eos_lldp_global(#33)
- [x] eos_lldp_interfaces(#33)
- [x] eos_lag_interfaces (#35)
- [x] eos_vlans(#37)

##### ISSUE TYPE
- Feature Idea

**Comment by trishnaguha** [comment]
Please take care of adding fully qualified collection name in the examples for these modules in the same PRs as well.
