### ISSUE TITLE
 Support httpapi in resource modules

### ISSUE THREAD

**Issue by Qalthos** [ansible-collections/arista.eos#28]
##### SUMMARY

- [x] Add support to httpapi plugin (#29)
- [x] Migrate tests to cover both connections:
  - [x] eos_acls (#34)
  - [x] eos_acl_interfaces (#34)
  - [x] eos_interfaces (#29)
  - [x] eos_l2_interfaces (#34)
  - [x] eos_l3_interfaces (#34)
  - [x] eos_lacp (#40)
  - [x] eos_lacp_interfaces (#40)
  - [x] eos_lag_interfaces (#40)
  - [x] eos_lldp_global (#40)
  - [x] eos_lldp_interfaces (#40)
  - [x] eos_ospfv2 (#19)
  - [x] eos_static_routes (#47)
  - [x] eos_vlans (#47)

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

httpapi/eos.py
